version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: petstore-db
    environment:
      POSTGRES_DB: petstore1
      POSTGRES_USER: petstore_1user
      POSTGRES_PASSWORD: petstore_1pass
    ports:
      - "5432:5432"
    volumes:
      - petstore_data:/var/lib/postgresql/data

volumes:
  petstore_data:

